export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_ALL_ORDERS_REQUEST = "ORDER_ALL_ORDERS_REQUEST";
export const ORDER_ALL_ORDERS_SUCCESS = "ORDER_ALL_ORDERS_SUCCESS";
export const ORDER_ALL_ORDERS_FAIL = "ORDER_ALL_ORDERS_FAIL";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

export const ORDER_LIST_ALL_USER_ORDERS_REQUEST =
  "ORDERS_LIST_ALL_USER_ORDERS_REQUEST";
export const ORDERS_LIST_ALL_USER_ORDERS_SUCCESS =
  "ORDERS_LIST_ALL_USER_ORDERS_SUCCESS";
export const ORDERS_LIST_ALL_USER_ORDERS_FAIL =
  "ORDERS_LIST_ALL_USER_ORDERS_FAIL";
export const ORDERS_LIST_ALL_USER_ORDERS_RESET =
  "ORDERS_LIST_ALL_USER_ORDERS_RESET";
